<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-KK4KH27" failures="1" tests="4" name="Test" time="10.324" errors="0" timestamp="2024-01-03T12:07:03 IST">
  <testcase classname="TestPackage.TestExample" name="login" time="1.065"/>
  <testcase classname="TestPackage.TestExample" name="login" time="0.28">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/v1/index.html] but found [https://www.saucedemo.com/v1/inventory.html]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/v1/index.html] but found [https://www.saucedemo.com/v1/inventory.html]
at TestPackage.TestExample.login(TestExample.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="TestPackage.TestExample" name="login" time="0.609"/>
  <testcase classname="TestPackage.TestExample" name="login" time="5.412"/>
</testsuite> <!-- Test -->
